import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { Save, ChevronLeft, ChevronRight, Plus, X, Layers3, FileText, BookOpen, CheckCircle2, ArrowRight } from 'lucide-react';
import PageHeader from '../../components/PageHeader';
import Button from '../../components/Button';
import programAPI from '../../api/program';

const CreateProgram = () => {
  const navigate = useNavigate();
  const { programId } = useParams();
  const [currentStep, setCurrentStep] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [saving, setSaving] = useState(false);
  const [programData, setProgramData] = useState({
    name: '',
    code: '',
    description: '',
    duration: 6,
    price: 0,
    status: 'DRAFT',
  });
  const [modules, setModules] = useState([]);

  const totalSteps = 2;

  useEffect(() => {
    if (programId) {
      loadProgram();
    }
  }, [programId]);

  useEffect(() => {
    if (programId && currentStep === 2) {
      handleRefreshModules();
    }
  }, [programId, currentStep]);

  // Auto-save functionality
  useEffect(() => {
    if (programId) {
      const autoSaveTimer = setTimeout(() => {
        autoSave();
      }, 2000); // Auto-save after 2 seconds of inactivity

      return () => clearTimeout(autoSaveTimer);
    }
  }, [programData, modules, programId]);

  const loadProgram = async () => {
    try {
      const response = await programAPI.getProgramById(programId);
      if (response.success) {
        const program = response.data.program;
        setProgramData({
          name: program.name || '',
          code: program.code || '',
          description: program.description || '',
          duration: program.duration || 6,
          price: program.price || 0,
          status: program.status || 'DRAFT',
        });

        // Load modules
        const modulesResponse = await programAPI.getModulesByProgram(programId);
        if (modulesResponse.success && modulesResponse.data.modules) {
          setModules(modulesResponse.data.modules.map(m => ({
            ...m,
            objectives: m.objectives || []
          })));
        }
      }
    } catch (error) {
      console.error('Error loading program:', error);
      toast.error('Failed to load program');
    }
  };

  const autoSave = async () => {
    if (!programId) return;
    
    setSaving(true);
    try {
      await programAPI.updateProgram(programId, {
        ...programData,
        status: 'DRAFT', // Keep as draft until explicitly activated
      });
      // Silently save - don't show toast for auto-save
    } catch (error) {
      console.error('Auto-save failed:', error);
    } finally {
      setSaving(false);
    }
  };

  const generateProgramCode = (name) => {
    if (!name || !name.trim()) return '';
    // Convert to uppercase, replace spaces and special chars with hyphens, remove multiple hyphens
    return name
      .toUpperCase()
      .replace(/[^A-Z0-9\s]/g, '') // Remove special characters
      .replace(/\s+/g, '-') // Replace spaces with hyphens
      .replace(/-+/g, '-') // Replace multiple hyphens with single hyphen
      .replace(/^-|-$/g, ''); // Remove leading/trailing hyphens
  };

  const handleProgramChange = (field, value) => {
    const updatedData = { ...programData, [field]: value };
    
    // Auto-generate code when name changes (if code is empty or was auto-generated)
    if (field === 'name') {
      const autoGeneratedCode = generateProgramCode(value);
      // Only auto-update if code is empty or matches the previous auto-generated pattern
      if (!programData.code || programData.code === generateProgramCode(programData.name)) {
        updatedData.code = autoGeneratedCode;
      }
    }
    
    setProgramData(updatedData);
  };

  const handleCreateProgram = async () => {
    if (!programData.name.trim()) {
      toast.error('Program name is required');
      return;
    }

    setIsSubmitting(true);
    try {
      const response = await programAPI.createProgram(programData);
      if (response.success) {
        const newProgramId = response.data.program.id || response.data.program._id;
        toast.success('Program created successfully!');
        // Navigate to the same page but with programId
        navigate(`/program-manager/programs/create/${newProgramId}`, { replace: true });
        setCurrentStep(2); // Move to modules step
      }
    } catch (error) {
      console.error('Error creating program:', error);
      toast.error(error.message || 'Failed to create program');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleRefreshModules = async () => {
    if (!programId) return;
    try {
      const modulesResponse = await programAPI.getModulesByProgram(programId);
      if (modulesResponse.success && modulesResponse.data.modules) {
        setModules(modulesResponse.data.modules.map(m => ({
          ...m,
          objectives: m.objectives || []
        })));
      }
    } catch (error) {
      console.error('Error loading modules:', error);
    }
  };

  const handleDeleteModule = async (index) => {
    if (!window.confirm('Are you sure you want to delete this module?')) return;
    
    const module = modules[index];
    if (module.id || module._id) {
      try {
        await programAPI.updateModule(module.id || module._id, { status: 'DELETED' });
        toast.success('Module deleted');
        handleRefreshModules();
      } catch (error) {
        toast.error('Failed to delete module');
      }
    } else {
      setModules(modules.filter((_, i) => i !== index));
    }
  };

  const handleSaveAll = async () => {
    if (!programId) {
      await handleCreateProgram();
      return;
    }

    setIsSubmitting(true);
    try {
      // Save program
      await programAPI.updateProgram(programId, programData);

      // Save all modules
      for (const module of modules) {
        if (module.id || module._id) {
          await programAPI.updateModule(module.id || module._id, module);
        } else {
          await programAPI.createModule(programId, module);
        }
      }

      toast.success('All changes saved successfully!');
    } catch (error) {
      console.error('Error saving:', error);
      toast.error('Failed to save changes');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleActivateProgram = async () => {
    if (modules.length === 0) {
      toast.error('Please add at least one module before activating');
      return;
    }

    for (const module of modules) {
      if (!module.objectives || module.objectives.length === 0) {
        toast.error(`Module "${module.name}" must have at least one learning objective`);
        return;
      }
    }

    setIsSubmitting(true);
    try {
      await programAPI.updateProgram(programId, { ...programData, status: 'ACTIVE' });
      toast.success('Program activated successfully!');
      navigate('/program-manager/programs');
    } catch (error) {
      console.error('Error activating program:', error);
      toast.error('Failed to activate program');
    } finally {
      setIsSubmitting(false);
    }
  };

  const calculateStats = () => {
    const totalModules = modules.length;
    const totalObjectives = modules.reduce((sum, m) => sum + (m.objectives?.length || 0), 0);
    const totalDuration = modules.reduce((sum, m) => sum + (m.duration || 0), 0);
    return { totalModules, totalObjectives, totalDuration };
  };

  const stats = calculateStats();

  return (
    <>
      <PageHeader
        title={programId ? `Edit Program - ${programData.name || 'Untitled'}` : 'Create New Program'}
        description={programId ? 'Edit your program details and modules' : 'Create a new program with modules and learning objectives'}
        actions={
          <div className="flex items-center gap-2">
            {saving && (
              <span className="text-sm text-textMuted flex items-center gap-1">
                <Save className="h-4 w-4 animate-spin" />
                Saving...
              </span>
            )}
            <Button
              variant="ghost"
              onClick={() => navigate('/program-manager/programs')}
            >
              <ChevronLeft className="h-4 w-4 mr-2" />
              Back
            </Button>
            {programId && (
              <Button
                variant="primary"
                onClick={handleSaveAll}
                disabled={isSubmitting}
              >
                <Save className="h-4 w-4 mr-2" />
                Save Changes
              </Button>
            )}
          </div>
        }
      />

      {/* Progress Steps */}
      <div className="mb-8">
        <div className="flex items-center">
          {[1, 2].map((step) => (
            <div key={step} className="flex items-center flex-1">
              <div className="flex items-center">
                <div
                  className={`flex items-center justify-center w-12 h-12 rounded-xl border-2 transition-all ${
                    currentStep > step
                      ? 'bg-brand-500 border-brand-500 text-white shadow-md'
                      : currentStep === step
                      ? 'border-brand-500 text-brand-600 bg-brand-50 shadow-sm'
                      : 'border-gray-300 text-gray-400 bg-white'
                  }`}
                >
                  {currentStep > step ? (
                    <CheckCircle2 className="h-6 w-6" />
                  ) : (
                    <span className="font-bold text-base">{step}</span>
                  )}
                </div>
                <div className="ml-3">
                  <span
                    className={`block text-sm font-semibold ${
                      currentStep >= step ? 'text-text' : 'text-gray-400'
                    }`}
                  >
                    {step === 1 ? 'Program Details' : 'Add Modules'}
                  </span>
                  <span className="block text-xs text-textMuted mt-0.5">
                    {step === 1 ? 'Basic information' : 'Learning modules'}
                  </span>
                </div>
              </div>
              {step < totalSteps && (
                <div
                  className={`flex-1 h-1 mx-6 rounded-full transition-all ${
                    currentStep > step ? 'bg-brand-500' : 'bg-gray-200'
                  }`}
                />
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Step Content */}
      <div className="rounded-3xl border border-brintelli-border bg-white shadow-card p-8">
        {/* Step 1: Program Details */}
        {currentStep === 1 && (
          <div className="space-y-6">
            <div className="border-b border-brintelli-border pb-4">
              <h3 className="text-2xl font-semibold text-text">Program Information</h3>
              <p className="mt-1 text-sm text-textMuted">Enter the basic details for your program</p>
            </div>
            
            <div className="space-y-2">
              <label className="block text-sm font-semibold text-text">
                Program Name <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                value={programData.name}
                onChange={(e) => handleProgramChange('name', e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-xl bg-white text-text focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-500/10 transition-all"
                placeholder="e.g., Full Stack Web Development"
              />
            </div>

            <div className="space-y-2">
              <label className="block text-sm font-semibold text-text">
                Program Code
                <span className="text-xs text-textMuted ml-2 font-normal">(Auto-generated)</span>
              </label>
              <input
                type="text"
                value={programData.code}
                onChange={(e) => handleProgramChange('code', e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-xl bg-gray-50 text-text focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-500/10 transition-all"
                placeholder="Will be generated from program name"
                readOnly={!programData.code || programData.code === generateProgramCode(programData.name)}
              />
              {programData.name && (
                <p className="text-xs text-textMuted">
                  Code is automatically generated from the program name. You can edit it manually if needed.
                </p>
              )}
            </div>

            <div className="space-y-2">
              <label className="block text-sm font-semibold text-text">Description</label>
              <textarea
                value={programData.description}
                onChange={(e) => handleProgramChange('description', e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-xl bg-white text-text focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-500/10 transition-all resize-none"
                rows={4}
                placeholder="Describe the program..."
              />
            </div>

            <div className="grid grid-cols-3 gap-6">
              <div className="space-y-2">
                <label className="block text-sm font-semibold text-text">Duration (months)</label>
                <input
                  type="number"
                  value={programData.duration}
                  onChange={(e) => handleProgramChange('duration', parseInt(e.target.value) || 0)}
                  className="w-full px-4 py-3 border border-gray-300 rounded-xl bg-white text-text focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-500/10 transition-all"
                  min="1"
                />
              </div>
              <div className="space-y-2">
                <label className="block text-sm font-semibold text-text">Price (₹)</label>
                <input
                  type="number"
                  value={programData.price}
                  onChange={(e) => handleProgramChange('price', parseFloat(e.target.value) || 0)}
                  className="w-full px-4 py-3 border border-gray-300 rounded-xl bg-white text-text focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-500/10 transition-all"
                  min="0"
                  step="0.01"
                />
              </div>
              <div className="space-y-2">
                <label className="block text-sm font-semibold text-text">Status</label>
                <select
                  value={programData.status}
                  onChange={(e) => handleProgramChange('status', e.target.value)}
                  className="w-full px-4 py-3 border border-gray-300 rounded-xl bg-gray-50 text-text focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-500/10 transition-all"
                  disabled
                >
                  <option value="DRAFT">Draft</option>
                  <option value="ACTIVE">Active</option>
                  <option value="ARCHIVED">Archived</option>
                </select>
                <p className="text-xs text-textMuted">Status will be Active when you complete the program</p>
              </div>
            </div>

            <div className="flex justify-end gap-3 pt-6 border-t border-gray-200">
              <Button
                variant="ghost"
                onClick={() => navigate('/program-manager/programs')}
              >
                Cancel
              </Button>
              <Button
                variant="primary"
                onClick={programId ? () => setCurrentStep(2) : handleCreateProgram}
                disabled={isSubmitting || !programData.name.trim()}
              >
                {programId ? 'Continue to Modules' : isSubmitting ? 'Creating...' : 'Create Program'}
                <ChevronRight className="h-4 w-4 ml-2" />
              </Button>
            </div>
          </div>
        )}

        {/* Step 2: Modules */}
        {currentStep === 2 && programId && (
          <div className="space-y-6">
            <div className="flex items-center justify-between border-b border-gray-200 pb-4">
              <div>
                <h3 className="text-2xl font-semibold text-text mb-3">Modules</h3>
                <div className="flex items-center gap-6 text-sm">
                  <span className="flex items-center gap-2 text-textMuted">
                    <Layers3 className="h-4 w-4" />
                    <span className="font-medium">{stats.totalModules} Modules</span>
                  </span>
                  <span className="flex items-center gap-2 text-textMuted">
                    <BookOpen className="h-4 w-4" />
                    <span className="font-medium">{stats.totalObjectives} Objectives</span>
                  </span>
                  <span className="flex items-center gap-2 text-textMuted">
                    <FileText className="h-4 w-4" />
                    <span className="font-medium">{stats.totalDuration}h Duration</span>
                  </span>
                </div>
              </div>
              <Button variant="primary" onClick={() => {
                navigate(`/program-manager/programs/${programId}/modules/new`);
              }}>
                <Plus className="h-4 w-4 mr-2" />
                Add Module
              </Button>
            </div>

            {modules.length === 0 ? (
              <div className="text-center py-20 border-2 border-dashed border-gray-300 rounded-3xl bg-gray-50">
                <Layers3 className="h-16 w-16 text-gray-400 mx-auto mb-4" />
                <p className="text-lg font-semibold text-text mb-2">No modules added yet</p>
                <p className="text-sm text-textMuted mb-6">
                  Start by adding your first module to the program
                </p>
                <Button variant="primary" onClick={() => {
                  navigate(`/program-manager/programs/${programId}/modules/new`);
                }}>
                  <Plus className="h-4 w-4 mr-2" />
                  Add Your First Module
                </Button>
              </div>
            ) : (
              <div className="space-y-3">
                {modules.map((module, moduleIndex) => (
                  <div
                    key={moduleIndex}
                    className="border border-gray-200 rounded-2xl p-6 bg-white hover:border-brand-500 hover:shadow-md transition-all cursor-pointer"
                    onClick={() => navigate(`/program-manager/programs/${programId}/modules/${module.id || module._id}`)}
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <h4 className="text-lg font-semibold text-text">{module.name || `Module ${moduleIndex + 1}`}</h4>
                          <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                            module.status === 'ACTIVE' ? 'bg-green-50 text-green-700 border border-green-200' :
                            module.status === 'COMPLETED' ? 'bg-blue-50 text-blue-700 border border-blue-200' :
                            'bg-gray-50 text-gray-700 border border-gray-200'
                          }`}>
                            {module.status || 'DRAFT'}
                          </span>
                        </div>
                        {module.description && (
                          <p className="text-sm text-textMuted mb-3">{module.description}</p>
                        )}
                        <div className="flex items-center gap-6 text-xs font-medium text-textMuted">
                          <span>Order: {module.order}</span>
                          <span>Duration: {module.duration || 0}h</span>
                          {module.subModules && module.subModules.length > 0 && (
                            <span>{module.subModules.length} Sub-Module{module.subModules.length !== 1 ? 's' : ''}</span>
                          )}
                        </div>
                      </div>
                      <div className="flex items-center gap-2" onClick={(e) => e.stopPropagation()}>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => navigate(`/program-manager/programs/${programId}/modules/${module.id || module._id}`)}
                          className="text-text hover:text-brand-600"
                        >
                          Edit
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleDeleteModule(moduleIndex)}
                          className="text-red-500 hover:text-red-700 hover:bg-red-50"
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>

                    {/* Sub-Modules Link */}
                    <div className="mt-4 pt-4 border-t border-gray-200">
                      <Button
                        variant="secondary"
                        size="sm"
                        onClick={(e) => {
                          e.stopPropagation();
                          navigate(`/program-manager/programs/${programId}/modules/${module.id || module._id}`);
                        }}
                        className="w-full justify-between"
                      >
                        <span className="flex items-center gap-2">
                          <Layers3 className="h-4 w-4" />
                          Manage Sub-Modules
                        </span>
                        <ArrowRight className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}

            <div className="flex justify-between items-center pt-6 border-t border-brintelli-border">
              <Button
                variant="ghost"
                onClick={() => setCurrentStep(1)}
              >
                <ChevronLeft className="h-4 w-4 mr-2" />
                Back to Details
              </Button>
              <div className="flex gap-2">
                <Button
                  variant="ghost"
                  onClick={handleSaveAll}
                  disabled={isSubmitting}
                >
                  <Save className="h-4 w-4 mr-2" />
                  Save Progress
                </Button>
                <Button
                  variant="primary"
                  onClick={handleActivateProgram}
                  disabled={isSubmitting || modules.length === 0}
                >
                  {isSubmitting ? 'Activating...' : 'Activate Program'}
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>

    </>
  );
};


export default CreateProgram;

