import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { 
  Save, ChevronLeft, Plus, X, Layers3, FileText, BookOpen, Target, 
  ChevronDown, ChevronUp, Edit2, Trash2, Upload, Loader2, Link, File, 
  Database, Video, ExternalLink, Link2, CheckCircle2, Clock
} from 'lucide-react';
import PageHeader from '../../components/PageHeader';
import Button from '../../components/Button';
import Modal from '../../components/Modal';
import programAPI from '../../api/program';
import uploadAPI from '../../api/upload';
import { getProxyUrl } from '../../utils/s3Helper';

const ProgramBuilder = () => {
  const navigate = useNavigate();
  const { programId } = useParams();
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);
  
  // Program data
  const [programData, setProgramData] = useState({
    name: '',
    code: '',
    description: '',
    duration: 6,
    price: 0,
    status: 'DRAFT',
  });

  // Modules with nested objectives
  const [modules, setModules] = useState([]);
  const [expandedModules, setExpandedModules] = useState(new Set());
  const [expandedObjectives, setExpandedObjectives] = useState(new Set());

  // Resource upload state
  const [uploadingFiles, setUploadingFiles] = useState({});
  const [showResourceModal, setShowResourceModal] = useState(false);
  const [editingResource, setEditingResource] = useState(null);
  const [resourceFormData, setResourceFormData] = useState({
    type: 'DOCUMENT',
    forWhom: 'LEARNER',
    title: '',
    url: '',
    content: '',
    file: null,
  });

  useEffect(() => {
    if (programId) {
      loadProgram();
    } else {
      setLoading(false);
    }
  }, [programId]);

  // Auto-save functionality
  useEffect(() => {
    if (programId && programData.name) {
      const autoSaveTimer = setTimeout(() => {
        autoSave();
      }, 2000);
      return () => clearTimeout(autoSaveTimer);
    }
  }, [programData, modules, programId]);

  const loadProgram = async () => {
    try {
      setLoading(true);
      const response = await programAPI.getProgramById(programId);
      if (response.success) {
        const program = response.data.program;
        setProgramData({
          name: program.name || '',
          code: program.code || '',
          description: program.description || '',
          duration: program.duration || 6,
          price: program.price || 0,
          status: program.status || 'DRAFT',
        });

        // Load modules with objectives
        const modulesResponse = await programAPI.getModulesByProgram(programId);
        if (modulesResponse.success && modulesResponse.data.modules) {
          const loadedModules = modulesResponse.data.modules.map(m => ({
            ...m,
            objectives: m.objectives || []
          }));
          setModules(loadedModules);
          // Expand first module by default
          if (loadedModules.length > 0) {
            setExpandedModules(new Set([0]));
          }
        }
      }
    } catch (error) {
      console.error('Error loading program:', error);
      toast.error('Failed to load program');
    } finally {
      setLoading(false);
    }
  };

  const autoSave = async () => {
    if (!programId) return;
    setSaving(true);
    try {
      await programAPI.updateProgram(programId, {
        ...programData,
        status: 'DRAFT',
      });
    } catch (error) {
      console.error('Auto-save failed:', error);
    } finally {
      setSaving(false);
    }
  };

  const generateProgramCode = (name) => {
    if (!name || !name.trim()) return '';
    return name
      .toUpperCase()
      .replace(/[^A-Z0-9\s]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
  };

  const handleProgramChange = (field, value) => {
    const updatedData = { ...programData, [field]: value };
    if (field === 'name') {
      const autoGeneratedCode = generateProgramCode(value);
      if (!programData.code || programData.code === generateProgramCode(programData.name)) {
        updatedData.code = autoGeneratedCode;
      }
    }
    setProgramData(updatedData);
  };

  const handleCreateProgram = async () => {
    if (!programData.name.trim()) {
      toast.error('Program name is required');
      return;
    }

    setSaving(true);
    try {
      const response = await programAPI.createProgram(programData);
      if (response.success) {
        const newProgramId = response.data.program.id || response.data.program._id;
        toast.success('Program created successfully!');
        navigate(`/program-manager/programs/builder/${newProgramId}`, { replace: true });
      }
    } catch (error) {
      console.error('Error creating program:', error);
      toast.error(error.message || 'Failed to create program');
    } finally {
      setSaving(false);
    }
  };

  const handleSaveAll = async () => {
    if (!programId) {
      await handleCreateProgram();
      return;
    }

    setSaving(true);
    try {
      // Save program
      await programAPI.updateProgram(programId, programData);

      // Save all modules
      for (const module of modules) {
        if (module.id || module._id) {
          await programAPI.updateModule(module.id || module._id, module);
        } else {
          const response = await programAPI.createModule(programId, module);
          if (response.success) {
            const newModuleId = response.data.module?.id || response.data.module?._id;
            module.id = newModuleId;
            module._id = newModuleId;
          }
        }
      }

      toast.success('All changes saved successfully!');
    } catch (error) {
      console.error('Error saving:', error);
      toast.error(error.message || 'Failed to save changes');
    } finally {
      setSaving(false);
    }
  };

  // Module management
  const addModule = () => {
    const newModule = {
      name: '',
      description: '',
      order: modules.length,
      duration: 0,
      status: 'DRAFT',
      objectives: []
    };
    setModules([...modules, newModule]);
    setExpandedModules(new Set([...expandedModules, modules.length]));
  };

  const removeModule = async (index) => {
    if (!window.confirm('Are you sure you want to delete this module? All objectives will be deleted.')) return;
    
    const module = modules[index];
    if (module.id || module._id) {
      try {
        await programAPI.updateModule(module.id || module._id, { status: 'DELETED' });
        toast.success('Module deleted');
      } catch (error) {
        toast.error('Failed to delete module');
        return;
      }
    }
    
    setModules(modules.filter((_, i) => i !== index));
    const newExpanded = new Set(expandedModules);
    newExpanded.delete(index);
    setExpandedModules(newExpanded);
  };

  const updateModule = (index, field, value) => {
    const updated = [...modules];
    updated[index] = { ...updated[index], [field]: value };
    setModules(updated);
  };

  const toggleModule = (index) => {
    const newExpanded = new Set(expandedModules);
    if (newExpanded.has(index)) {
      newExpanded.delete(index);
    } else {
      newExpanded.add(index);
    }
    setExpandedModules(newExpanded);
  };

  // Objective management
  const addObjective = (moduleIndex) => {
    const updated = [...modules];
    if (!updated[moduleIndex].objectives) {
      updated[moduleIndex].objectives = [];
    }
    updated[moduleIndex].objectives.push({
      text: '',
      minDuration: 0,
      resources: [],
      assignments: [],
      practiceTasks: [],
    });
    setModules(updated);
    
    const objectiveKey = `${moduleIndex}-${updated[moduleIndex].objectives.length - 1}`;
    setExpandedObjectives(new Set([...expandedObjectives, objectiveKey]));
  };

  const removeObjective = (moduleIndex, objectiveIndex) => {
    const updated = [...modules];
    updated[moduleIndex].objectives = updated[moduleIndex].objectives.filter((_, i) => i !== objectiveIndex);
    setModules(updated);
    
    const objectiveKey = `${moduleIndex}-${objectiveIndex}`;
    const newExpanded = new Set(expandedObjectives);
    newExpanded.delete(objectiveKey);
    setExpandedObjectives(newExpanded);
  };

  const updateObjective = (moduleIndex, objectiveIndex, field, value) => {
    const updated = [...modules];
    updated[moduleIndex].objectives[objectiveIndex] = {
      ...updated[moduleIndex].objectives[objectiveIndex],
      [field]: value
    };
    setModules(updated);
  };

  const toggleObjective = (moduleIndex, objectiveIndex) => {
    const objectiveKey = `${moduleIndex}-${objectiveIndex}`;
    const newExpanded = new Set(expandedObjectives);
    if (newExpanded.has(objectiveKey)) {
      newExpanded.delete(objectiveKey);
    } else {
      newExpanded.add(objectiveKey);
    }
    setExpandedObjectives(newExpanded);
  };

  // Resource management
  const handleAddResource = (moduleIndex, objectiveIndex) => {
    setEditingResource({ moduleIndex, objectiveIndex, resourceIndex: null });
    setResourceFormData({
      type: 'DOCUMENT',
      forWhom: 'LEARNER',
      title: '',
      url: '',
      content: '',
      file: null,
    });
    setShowResourceModal(true);
  };

  const handleEditResource = (moduleIndex, objectiveIndex, resourceIndex) => {
    const resource = modules[moduleIndex].objectives[objectiveIndex].resources[resourceIndex];
    setEditingResource({ moduleIndex, objectiveIndex, resourceIndex });
    setResourceFormData({
      type: resource.type || 'DOCUMENT',
      forWhom: resource.forWhom || 'LEARNER',
      title: resource.title || '',
      url: resource.url || '',
      content: resource.content || '',
      file: null,
    });
    setShowResourceModal(true);
  };

  const handleSaveResource = async () => {
    if (!resourceFormData.title.trim()) {
      toast.error('Resource title is required');
      return;
    }

    if (resourceFormData.type === 'LINK' && !resourceFormData.url.trim()) {
      toast.error('URL is required for links');
      return;
    }

    if (resourceFormData.type === 'NOTE' && !resourceFormData.content.trim()) {
      toast.error('Content is required for notes');
      return;
    }

    // Handle file upload if needed
    let resourceData = { ...resourceFormData };
    if (resourceFormData.file && (resourceFormData.type === 'DOCUMENT' || resourceFormData.type === 'VIDEO')) {
      try {
        const folder = 'program-resources';
        const response = await uploadAPI.uploadFile(resourceFormData.file, folder);
        if (response.success) {
          resourceData.url = response.data.url;
          resourceData.fileKey = response.data.key;
          resourceData.fileName = response.data.originalName || resourceFormData.file.name;
          resourceData.fileSize = response.data.size || resourceFormData.file.size;
          resourceData.mimeType = response.data.mimeType || resourceFormData.file.type;
        }
      } catch (error) {
        toast.error('Failed to upload file');
        return;
      }
    }

    const updated = [...modules];
    const { moduleIndex, objectiveIndex, resourceIndex } = editingResource;

    if (resourceIndex === null) {
      // Add new resource
      if (!updated[moduleIndex].objectives[objectiveIndex].resources) {
        updated[moduleIndex].objectives[objectiveIndex].resources = [];
      }
      updated[moduleIndex].objectives[objectiveIndex].resources.push(resourceData);
    } else {
      // Update existing resource
      updated[moduleIndex].objectives[objectiveIndex].resources[resourceIndex] = resourceData;
    }

    setModules(updated);
    setShowResourceModal(false);
    setEditingResource(null);
    setResourceFormData({
      type: 'DOCUMENT',
      forWhom: 'LEARNER',
      title: '',
      url: '',
      content: '',
      file: null,
    });
    toast.success('Resource saved');
  };

  const handleDeleteResource = (moduleIndex, objectiveIndex, resourceIndex) => {
    const updated = [...modules];
    updated[moduleIndex].objectives[objectiveIndex].resources = 
      updated[moduleIndex].objectives[objectiveIndex].resources.filter((_, i) => i !== resourceIndex);
    setModules(updated);
    toast.success('Resource deleted');
  };

  const getResourceIcon = (type) => {
    switch (type) {
      case 'DOCUMENT': return <File className="h-4 w-4" />;
      case 'LINK': return <Link className="h-4 w-4" />;
      case 'VIDEO': return <Video className="h-4 w-4" />;
      case 'NOTE': return <FileText className="h-4 w-4" />;
      default: return <FileText className="h-4 w-4" />;
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-brand-500 mx-auto mb-4"></div>
          <p className="text-textMuted">Loading program...</p>
        </div>
      </div>
    );
  }

  return (
    <>
      <PageHeader
        title={programId ? `Edit Program` : 'Create Program'}
        description={programId ? 'Edit program, modules, and objectives' : 'Create a new program with modules and objectives'}
        actions={
          <div className="flex items-center gap-2">
            {saving && (
              <span className="text-sm text-textMuted flex items-center gap-1">
                <Save className="h-4 w-4 animate-spin" />
                Saving...
              </span>
            )}
            <Button variant="ghost" onClick={() => navigate('/program-manager/programs')}>
              <ChevronLeft className="h-4 w-4 mr-2" />
              Back to Programs
            </Button>
            <Button variant="primary" onClick={handleSaveAll}>
              <Save className="h-4 w-4 mr-2" />
              {programId ? 'Save All Changes' : 'Create Program'}
            </Button>
          </div>
        }
      />

      <div className="space-y-6">
        {/* Program Details */}
        <div className="rounded-2xl border border-brintelli-border bg-brintelli-card shadow-soft p-6">
          <h2 className="text-xl font-semibold text-text mb-4 flex items-center gap-2">
            <Layers3 className="h-5 w-5" />
            Program Details
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-text mb-2">
                Program Name <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                value={programData.name}
                onChange={(e) => handleProgramChange('name', e.target.value)}
                className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                placeholder="Enter program name"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-text mb-2">Program Code</label>
              <input
                type="text"
                value={programData.code}
                onChange={(e) => handleProgramChange('code', e.target.value)}
                className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                placeholder="Auto-generated from name"
              />
            </div>
            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-text mb-2">Description</label>
              <textarea
                value={programData.description}
                onChange={(e) => handleProgramChange('description', e.target.value)}
                className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                rows={3}
                placeholder="Enter program description"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-text mb-2">Duration (months)</label>
              <input
                type="number"
                value={programData.duration}
                onChange={(e) => handleProgramChange('duration', parseInt(e.target.value) || 0)}
                className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                min="0"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-text mb-2">Price (₹)</label>
              <input
                type="number"
                value={programData.price}
                onChange={(e) => handleProgramChange('price', parseFloat(e.target.value) || 0)}
                className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                min="0"
                step="0.01"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-text mb-2">Status</label>
              <select
                value={programData.status}
                onChange={(e) => handleProgramChange('status', e.target.value)}
                className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
              >
                <option value="DRAFT">Draft</option>
                <option value="ACTIVE">Active</option>
                <option value="INACTIVE">Inactive</option>
              </select>
            </div>
          </div>
        </div>

        {/* Modules Section */}
        <div className="rounded-2xl border border-brintelli-border bg-brintelli-card shadow-soft p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold text-text flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Modules ({modules.length})
            </h2>
            <Button variant="secondary" size="sm" onClick={addModule}>
              <Plus className="h-4 w-4 mr-2" />
              Add Module
            </Button>
          </div>

          <div className="space-y-4">
            {modules.map((module, moduleIndex) => (
              <div key={moduleIndex} className="border border-brintelli-border rounded-lg overflow-hidden">
                <div className="bg-brintelli-baseAlt/30 p-4 flex items-center justify-between">
                  <div className="flex items-center gap-3 flex-1">
                    <button
                      onClick={() => toggleModule(moduleIndex)}
                      className="text-text hover:text-brand-500"
                    >
                      {expandedModules.has(moduleIndex) ? (
                        <ChevronUp className="h-5 w-5" />
                      ) : (
                        <ChevronDown className="h-5 w-5" />
                      )}
                    </button>
                    <div className="flex-1">
                      <input
                        type="text"
                        value={module.name || ''}
                        onChange={(e) => updateModule(moduleIndex, 'name', e.target.value)}
                        className="text-lg font-semibold text-text bg-transparent border-none outline-none w-full"
                        placeholder="Module Name"
                      />
                      <p className="text-sm text-textMuted">
                        {module.objectives?.length || 0} objectives
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => removeModule(moduleIndex)}
                      className="text-red-500 hover:text-red-700"
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>

                {expandedModules.has(moduleIndex) && (
                  <div className="p-4 space-y-4 bg-brintelli-card">
                    {/* Module Details */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="md:col-span-2">
                        <label className="block text-sm font-medium text-text mb-2">Description</label>
                        <textarea
                          value={module.description || ''}
                          onChange={(e) => updateModule(moduleIndex, 'description', e.target.value)}
                          className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                          rows={2}
                          placeholder="Module description"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-text mb-2">Duration (hours)</label>
                        <input
                          type="number"
                          value={module.duration || 0}
                          onChange={(e) => updateModule(moduleIndex, 'duration', parseInt(e.target.value) || 0)}
                          className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                          min="0"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-text mb-2">Order</label>
                        <input
                          type="number"
                          value={module.order || moduleIndex}
                          onChange={(e) => updateModule(moduleIndex, 'order', parseInt(e.target.value) || 0)}
                          className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                          min="0"
                        />
                      </div>
                    </div>

                    {/* Objectives */}
                    <div className="border-t border-brintelli-border pt-4">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-md font-semibold text-text flex items-center gap-2">
                          <Target className="h-4 w-4" />
                          Learning Objectives ({module.objectives?.length || 0})
                        </h3>
                        <Button variant="ghost" size="sm" onClick={() => addObjective(moduleIndex)}>
                          <Plus className="h-4 w-4 mr-2" />
                          Add Objective
                        </Button>
                      </div>

                      <div className="space-y-3">
                        {module.objectives?.map((objective, objectiveIndex) => (
                          <div key={objectiveIndex} className="border border-brintelli-border rounded-lg overflow-hidden">
                            <div className="bg-brintelli-baseAlt/20 p-3 flex items-center justify-between">
                              <div className="flex items-center gap-2 flex-1">
                                <button
                                  onClick={() => toggleObjective(moduleIndex, objectiveIndex)}
                                  className="text-text hover:text-brand-500"
                                >
                                  {expandedObjectives.has(`${moduleIndex}-${objectiveIndex}`) ? (
                                    <ChevronUp className="h-4 w-4" />
                                  ) : (
                                    <ChevronDown className="h-4 w-4" />
                                  )}
                                </button>
                                <input
                                  type="text"
                                  value={objective.text || ''}
                                  onChange={(e) => updateObjective(moduleIndex, objectiveIndex, 'text', e.target.value)}
                                  className="flex-1 text-sm font-medium text-text bg-transparent border-none outline-none"
                                  placeholder="Learning objective"
                                />
                                <span className="text-xs text-textMuted">
                                  {objective.resources?.length || 0} resources
                                </span>
                              </div>
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => removeObjective(moduleIndex, objectiveIndex)}
                                className="text-red-500 hover:text-red-700"
                              >
                                <X className="h-4 w-4" />
                              </Button>
                            </div>

                            {expandedObjectives.has(`${moduleIndex}-${objectiveIndex}`) && (
                              <div className="p-3 space-y-3 bg-brintelli-card">
                                <div>
                                  <label className="block text-sm font-medium text-text mb-2">Objective Text</label>
                                  <textarea
                                    value={objective.text || ''}
                                    onChange={(e) => updateObjective(moduleIndex, objectiveIndex, 'text', e.target.value)}
                                    className="w-full px-3 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text text-sm"
                                    rows={2}
                                    placeholder="Describe what students will learn"
                                  />
                                </div>
                                <div>
                                  <label className="block text-sm font-medium text-text mb-2">Minimum Duration (minutes)</label>
                                  <input
                                    type="number"
                                    value={objective.minDuration || 0}
                                    onChange={(e) => updateObjective(moduleIndex, objectiveIndex, 'minDuration', parseInt(e.target.value) || 0)}
                                    className="w-full px-3 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text text-sm"
                                    min="0"
                                  />
                                </div>

                                {/* Resources */}
                                <div>
                                  <div className="flex items-center justify-between mb-2">
                                    <label className="block text-sm font-medium text-text">Resources</label>
                                    <Button
                                      variant="ghost"
                                      size="sm"
                                      onClick={() => handleAddResource(moduleIndex, objectiveIndex)}
                                    >
                                      <Plus className="h-4 w-4 mr-1" />
                                      Add Resource
                                    </Button>
                                  </div>
                                  <div className="space-y-2">
                                    {objective.resources?.map((resource, resourceIndex) => (
                                      <div key={resourceIndex} className="flex items-center justify-between p-2 bg-brintelli-baseAlt/20 rounded border border-brintelli-border">
                                        <div className="flex items-center gap-2 flex-1 min-w-0">
                                          {getResourceIcon(resource.type)}
                                          <div className="flex-1 min-w-0">
                                            <span className="text-sm text-text font-medium block truncate">{resource.title}</span>
                                            <div className="flex items-center gap-2 text-xs text-textMuted">
                                              <span>({resource.type})</span>
                                              {resource.url && (
                                                <a 
                                                  href={getProxyUrl(resource.url, resource.fileKey)} 
                                                  target="_blank" 
                                                  rel="noopener noreferrer"
                                                  className="text-brand-500 hover:text-brand-700 flex items-center gap-1 truncate"
                                                  onClick={(e) => e.stopPropagation()}
                                                >
                                                  <ExternalLink className="h-3 w-3 flex-shrink-0" />
                                                  <span className="truncate">
                                                    {resource.url.includes('s3.amazonaws.com') || resource.url.includes('cloudfront.net') 
                                                      ? 'S3 File' 
                                                      : resource.url}
                                                  </span>
                                                </a>
                                              )}
                                              {resource.fileName && (
                                                <span className="text-textMuted">• {resource.fileName}</span>
                                              )}
                                              {resource.fileSize && (
                                                <span className="text-textMuted">
                                                  • ({(resource.fileSize / 1024).toFixed(2)} KB)
                                                </span>
                                              )}
                                            </div>
                                          </div>
                                        </div>
                                        <div className="flex items-center gap-1 flex-shrink-0">
                                          <Button
                                            variant="ghost"
                                            size="sm"
                                            onClick={() => handleEditResource(moduleIndex, objectiveIndex, resourceIndex)}
                                          >
                                            <Edit2 className="h-3 w-3" />
                                          </Button>
                                          <Button
                                            variant="ghost"
                                            size="sm"
                                            onClick={() => handleDeleteResource(moduleIndex, objectiveIndex, resourceIndex)}
                                            className="text-red-500"
                                          >
                                            <X className="h-3 w-3" />
                                          </Button>
                                        </div>
                                      </div>
                                    ))}
                                    {(!objective.resources || objective.resources.length === 0) && (
                                      <p className="text-sm text-textMuted italic">No resources added</p>
                                    )}
                                  </div>
                                </div>
                              </div>
                            )}
                          </div>
                        ))}
                        {(!module.objectives || module.objectives.length === 0) && (
                          <p className="text-sm text-textMuted italic text-center py-4">No objectives added</p>
                        )}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            ))}
            {modules.length === 0 && (
              <p className="text-sm text-textMuted italic text-center py-8">No modules added. Click "Add Module" to get started.</p>
            )}
          </div>
        </div>
      </div>

      {/* Resource Modal */}
      {showResourceModal && (
        <Modal
          isOpen={showResourceModal}
          onClose={() => {
            setShowResourceModal(false);
            setEditingResource(null);
            setResourceFormData({
              type: 'DOCUMENT',
              forWhom: 'LEARNER',
              title: '',
              url: '',
              content: '',
              file: null,
            });
          }}
          title={editingResource?.resourceIndex !== null ? 'Edit Resource' : 'Add Resource'}
        >
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-text mb-2">Resource Type</label>
              <select
                value={resourceFormData.type}
                onChange={(e) => setResourceFormData({ ...resourceFormData, type: e.target.value })}
                className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
              >
                <option value="DOCUMENT">Document</option>
                <option value="LINK">Link</option>
                <option value="VIDEO">Video</option>
                <option value="NOTE">Note</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-text mb-2">For</label>
              <select
                value={resourceFormData.forWhom}
                onChange={(e) => setResourceFormData({ ...resourceFormData, forWhom: e.target.value })}
                className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
              >
                <option value="LEARNER">Learner</option>
                <option value="TUTOR">Tutor</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-text mb-2">Title <span className="text-red-500">*</span></label>
              <input
                type="text"
                value={resourceFormData.title}
                onChange={(e) => setResourceFormData({ ...resourceFormData, title: e.target.value })}
                className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                placeholder="Resource title"
              />
            </div>
            {resourceFormData.type === 'LINK' && (
              <div>
                <label className="block text-sm font-medium text-text mb-2">URL <span className="text-red-500">*</span></label>
                <input
                  type="url"
                  value={resourceFormData.url}
                  onChange={(e) => setResourceFormData({ ...resourceFormData, url: e.target.value })}
                  className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                  placeholder="https://example.com"
                />
              </div>
            )}
            {(resourceFormData.type === 'DOCUMENT' || resourceFormData.type === 'VIDEO') && (
              <div>
                <label className="block text-sm font-medium text-text mb-2">Upload File</label>
                <input
                  type="file"
                  onChange={(e) => setResourceFormData({ ...resourceFormData, file: e.target.files[0] })}
                  className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                  accept={resourceFormData.type === 'VIDEO' ? 'video/*' : '.pdf,.doc,.docx,.txt,.xls,.xlsx,.ppt,.pptx'}
                />
                {resourceFormData.file && (
                  <p className="text-sm text-textMuted mt-1">
                    Selected: {resourceFormData.file.name} ({(resourceFormData.file.size / 1024).toFixed(2)} KB)
                  </p>
                )}
              </div>
            )}
            {resourceFormData.type === 'NOTE' && (
              <div>
                <label className="block text-sm font-medium text-text mb-2">Content <span className="text-red-500">*</span></label>
                <textarea
                  value={resourceFormData.content}
                  onChange={(e) => setResourceFormData({ ...resourceFormData, content: e.target.value })}
                  className="w-full px-4 py-2 border border-brintelli-border rounded-lg bg-brintelli-card text-text"
                  rows={5}
                  placeholder="Note content"
                />
              </div>
            )}
            <div className="flex gap-2 justify-end">
              <Button variant="ghost" onClick={() => setShowResourceModal(false)}>
                Cancel
              </Button>
              <Button variant="primary" onClick={handleSaveResource}>
                Save Resource
              </Button>
            </div>
          </div>
        </Modal>
      )}
    </>
  );
};

export default ProgramBuilder;

