import {
  LayoutDashboard,
  Users,
  GraduationCap,
  UserCheck,
  BookOpen,
  Calendar,
  CheckCircle2,
  Clock,
  UserPlus,
  AlertTriangle,
  MessageSquare,
  Video,
  FileText,
  Activity,
  TrendingUp,
  CalendarCheck,
  BarChart3,
  Target,
  Briefcase,
} from "lucide-react";

/**
 * LSM (Learning Success Manager) Navigation
 * 
 * LSM manages student onboarding, batch allocation, course assignment, and mentor allocation.
 */

export const lsmNav = [
  {
    id: "lsm-dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    path: "/lsm/dashboard",
    pageId: "lsm-dashboard",
    permissions: ["lsm:read"],
  },
  {
    id: "onboarding",
    label: "Onboarding",
    icon: UserPlus,
    path: "/lsm/onboarding",
    pageId: "lsm-onboarding",
    permissions: ["lsm:read"],
  },
  {
    id: "batches",
    label: "Batches",
    icon: Calendar,
    path: "/lsm/batches",
    pageId: "lsm-batches",
    permissions: ["lsm:read"],
  },
  {
    id: "mentors",
    label: "Mentors",
    icon: UserCheck,
    path: "/lsm/mentors",
    pageId: "lsm-mentors",
    permissions: ["lsm:read"],
  },
  {
    id: "profiles",
    label: "Student Profiles",
    icon: Users,
    path: "/lsm/profiles",
    pageId: "lsm-profiles",
    permissions: ["lsm:read"],
  },
  {
    id: "risk-students",
    label: "Risk Students",
    icon: AlertTriangle,
    path: "/lsm/risk-students",
    pageId: "lsm-risk-students",
    permissions: ["lsm:read"],
  },
  {
    id: "escalations",
    label: "Escalations",
    icon: MessageSquare,
    path: "/lsm/escalations",
    pageId: "lsm-escalations",
    permissions: ["lsm:read"],
  },
  {
    id: "sessions",
    label: "Sessions",
    icon: Video,
    path: "/lsm/sessions",
    pageId: "lsm-sessions",
    permissions: ["lsm:read"],
  },
  {
    id: "one-on-one",
    label: "1:1 Sessions",
    icon: UserCheck,
    path: "/lsm/one-on-one",
    pageId: "lsm-one-on-one",
    permissions: ["lsm:read"],
  },
  {
    id: "session-logs",
    label: "Session Logs",
    icon: FileText,
    path: "/lsm/session-logs",
    pageId: "lsm-session-logs",
    permissions: ["lsm:read"],
  },
  {
    id: "engagement",
    label: "Engagement",
    icon: Activity,
    path: "/lsm/engagement",
    pageId: "lsm-engagement",
    permissions: ["lsm:read"],
  },
  {
    id: "progress",
    label: "Progress",
    icon: TrendingUp,
    path: "/lsm/progress",
    pageId: "lsm-progress",
    permissions: ["lsm:read"],
  },
  {
    id: "attendance",
    label: "Attendance",
    icon: CalendarCheck,
    path: "/lsm/attendance",
    pageId: "lsm-attendance",
    permissions: ["lsm:read"],
  },
  {
    id: "performance",
    label: "Performance",
    icon: BarChart3,
    path: "/lsm/performance",
    pageId: "lsm-performance",
    permissions: ["lsm:read"],
  },
  {
    id: "weekly-reports",
    label: "Weekly Reports",
    icon: FileText,
    path: "/lsm/weekly-reports",
    pageId: "lsm-weekly-reports",
    permissions: ["lsm:read"],
  },
  {
    id: "readiness",
    label: "Readiness",
    icon: Target,
    path: "/lsm/readiness",
    pageId: "lsm-readiness",
    permissions: ["lsm:read"],
  },
  {
    id: "interview-prep",
    label: "Interview Prep",
    icon: Briefcase,
    path: "/lsm/interview-prep",
    pageId: "lsm-interview-prep",
    permissions: ["lsm:read"],
  },
];

export default lsmNav;

